python3 main.py \
    --num_epochs 13 \
    --mode onTest \
    --model_type Cate \
    --model_name distilbert-base-uncased \
    --train_batch_size 32 \
    --test_batch_size 32 \
    --save_logging_steps 500 \
    --learning_rate 5e-5 \
    --house_dim 512 \
    --beauty_dim 512 \
    --baby_dim 512 \
    --kitchen_dim 768 \

python3 main.py \
    --num_epochs 13 \
    --mode onTest \
    --model_type Cate \
    --model_name distilroberta-base \
    --train_batch_size 32 \
    --test_batch_size 32 \
    --save_logging_steps 500 \
    --learning_rate 5e-5 \
    --house_dim 768 \
    --beauty_dim 512 \
    --baby_dim 768 \
    --kitchen_dim 768 \

python3 main.py \
    --num_epochs 13 \
    --mode onTest \
    --model_type Cate \
    --model_name climatebert/distilroberta-base-climate-f \
    --train_batch_size 32 \
    --test_batch_size 32 \
    --save_logging_steps 500 \
    --learning_rate 5e-5 \
    --house_dim 512 \
    --beauty_dim 768 \
    --baby_dim 768 \
    --kitchen_dim 512 \

python3 main.py \
    --num_epochs 13 \
    --mode onTest \
    --model_type noCate \
    --model_name distilbert-base-uncased \
    --train_batch_size 32 \
    --test_batch_size 32 \
    --save_logging_steps 500 \
    --learning_rate 5e-5 \

python3 main.py \
    --num_epochs 13 \
    --mode onTest \
    --model_type noCate \
    --model_name distilroberta-base \
    --train_batch_size 32 \
    --test_batch_size 32 \
    --save_logging_steps 500 \
    --learning_rate 5e-5 \

python3 main.py \
    --num_epochs 13 \
    --mode onTest \
    --model_type noCate \
    --model_name climatebert/distilroberta-base-climate-f \
    --train_batch_size 32 \
    --test_batch_size 32 \
    --save_logging_steps 500 \
    --learning_rate 5e-5 \
